#! /bin/bash

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list.d/virtualbox.list
apt remove virtualbox virtualbox-5.1
apt update
apt-get -y install gcc make linux-headers-$(uname -r) dkms
apt update
apt-get install virtualbox-5.2
